export const strings = {
    title: "대전 코어스톤 골프대회",
    description: " 2025년 대전 코어스톤 주최 사내 골프 대회를 개최하려고 합니다. 여러분의 참석 여부를 물어보고자 하오니, 아래의 내용에 입력하여 주십시오.",
    eventDate: "2025-05-15",
    eventDateLabel: "행사일",
    eventLocation: "세종특별자치시 연기면 정안세종로 1569",
    eventLocationLabel: "행사 장소",
    nameLabel: "성명",
    emailLabel: "Email",
    accompanylabel: "참석 인원",
    lmkLabel: "참석 하시나요?",
    yesOption: "네, 참석합니다.",
    noOption: "아니오, 전 불참입니다.",
    submitButton: "답변 전송",
    thankYouMessage: "내용 작성에 감사합니다!",
    viewOnMapButton: "네이버 지도로 보기",
    sendFromEmail: "onboarding@resend.dev",
    sendToEmail: process.env.EMAIL_TO,
}